# Generated by Django 3.1.2 on 2020-10-20 12:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Codigo unico del producto', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('precio', models.CharField(max_length=13, verbose_name='PRECIO')),
                ('descripcion', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
