# Generated by Django 3.1.2 on 2020-11-05 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra',
            old_name='id',
            new_name='codigo',
        ),
    ]
