# Generated by Django 3.1.2 on 2020-11-25 23:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_auto_20201105_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Codigo unico del usuario', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('contra', models.CharField(max_length=60, verbose_name='Contra')),
            ],
        ),
    ]
